// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const placeholderUserModelType = z.literal('PlaceholderUser');

export type PlaceholderUserModelType = z.infer<typeof placeholderUserModelType>;
