// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  ProjectCollectionModelType,
  projectCollectionModelType,
} from '../memberships/models/project-collection-model-type';
import {
  ProjectCollectionModelLinks,
  projectCollectionModelLinks,
  projectCollectionModelLinksRequest,
  projectCollectionModelLinksResponse,
} from '../memberships/models/project-collection-model-links';
import {
  ProjectCollectionModelEmbedded,
  projectCollectionModelEmbedded,
  projectCollectionModelEmbeddedRequest,
  projectCollectionModelEmbeddedResponse,
} from '../memberships/models/project-collection-model-embedded';

/**
 * The shape of the model inside the application code - what the users use
 */
export const projectCollectionModel = z.lazy(() => {
  return z.object({
    _type: projectCollectionModelType,
    total: z.number().gte(0),
    count: z.number().gte(0),
    _links: projectCollectionModelLinks,
    pageSize: z.number().gte(0),
    offset: z.number().gte(0),
    _embedded: projectCollectionModelEmbedded,
  });
});

/**
 * 
 * @typedef  {ProjectCollectionModel} projectCollectionModel   
 * @property {ProjectCollectionModelType} 
 * @property {number} - The total amount of elements available in the collection.
 * @property {number} - Actual amount of elements in this response.
 * @property {ProjectCollectionModelLinks} 
 * @property {number} - The amount of elements per page. If not set by the request this value defaults to the server's system
settings.
 * @property {number} - The page offset indicating on which page the element collection starts.
 * @property {ProjectCollectionModelEmbedded} 
 */
export type ProjectCollectionModel = z.infer<typeof projectCollectionModel>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const projectCollectionModelResponse = z.lazy(() => {
  return z
    .object({
      _type: projectCollectionModelType,
      total: z.number().gte(0),
      count: z.number().gte(0),
      _links: projectCollectionModelLinksResponse,
      pageSize: z.number().gte(0),
      offset: z.number().gte(0),
      _embedded: projectCollectionModelEmbeddedResponse,
    })
    .transform((data) => ({
      _type: data['_type'],
      total: data['total'],
      count: data['count'],
      _links: data['_links'],
      pageSize: data['pageSize'],
      offset: data['offset'],
      _embedded: data['_embedded'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const projectCollectionModelRequest = z.lazy(() => {
  return z
    .object({
      _type: projectCollectionModelType,
      total: z.number().gte(0),
      count: z.number().gte(0),
      _links: projectCollectionModelLinksRequest,
      pageSize: z.number().gte(0),
      offset: z.number().gte(0),
      _embedded: projectCollectionModelEmbeddedRequest,
    })
    .transform((data) => ({
      _type: data['_type'],
      total: data['total'],
      count: data['count'],
      _links: data['_links'],
      pageSize: data['pageSize'],
      offset: data['offset'],
      _embedded: data['_embedded'],
    }));
});
