// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const customActionModelType = z.literal('CustomAction');

export type CustomActionModelType = z.infer<typeof customActionModelType>;
