// This file was generated by liblab | https://liblab.com/

export interface ListProjectsParams {
  filters?: string;
  sortBy?: string;
  select?: string;
}

export interface ListAvailableParentProjectCandidatesParams {
  filters?: string;
  of?: string;
  sortBy?: string;
}
