// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  ElementsDescription3,
  elementsDescription3,
  elementsDescription3Request,
  elementsDescription3Response,
} from './elements-description-3';
import { ElementsLinks8, elementsLinks8, elementsLinks8Request, elementsLinks8Response } from './elements-links-8';

/**
 * The shape of the model inside the application code - what the users use
 */
export const _embeddedElements10 = z.lazy(() => {
  return z.object({
    id: z.number().optional(),
    name: z.string(),
    description: elementsDescription3.optional(),
    startDate: z.string().optional(),
    endDate: z.string().optional(),
    status: z.string(),
    sharing: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
    _links: elementsLinks8.optional(),
  });
});

/**
 * Collection of Versions
 * @typedef  {_EmbeddedElements10} _embeddedElements10 - Collection of Versions - Collection of Versions
 * @property {number} - Version id
 * @property {string} - Version name
 * @property {ElementsDescription3}
 * @property {string}
 * @property {string}
 * @property {string} - The current status of the version
 * @property {string} - The current status of the version
 * @property {string} - Time of creation
 * @property {string} - Time of the most recent change to the version
 * @property {ElementsLinks8}
 */
export type _EmbeddedElements10 = z.infer<typeof _embeddedElements10>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const _embeddedElements10Response = z.lazy(() => {
  return z
    .object({
      id: z.number().optional(),
      name: z.string(),
      description: elementsDescription3Response.optional(),
      startDate: z.string().optional(),
      endDate: z.string().optional(),
      status: z.string(),
      sharing: z.string(),
      createdAt: z.string(),
      updatedAt: z.string(),
      _links: elementsLinks8Response.optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      description: data['description'],
      startDate: data['startDate'],
      endDate: data['endDate'],
      status: data['status'],
      sharing: data['sharing'],
      createdAt: data['createdAt'],
      updatedAt: data['updatedAt'],
      _links: data['_links'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const _embeddedElements10Request = z.lazy(() => {
  return z
    .object({
      id: z.number().optional(),
      name: z.string(),
      description: elementsDescription3Request.optional(),
      startDate: z.string().optional(),
      endDate: z.string().optional(),
      status: z.string(),
      sharing: z.string(),
      createdAt: z.string(),
      updatedAt: z.string(),
      _links: elementsLinks8Request.optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      description: data['description'],
      startDate: data['startDate'],
      endDate: data['endDate'],
      status: data['status'],
      sharing: data['sharing'],
      createdAt: data['createdAt'],
      updatedAt: data['updatedAt'],
      _links: data['_links'],
    }));
});
