// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { DescriptionFormat9, descriptionFormat9 } from './description-format-9';

/**
 * The shape of the model inside the application code - what the users use
 */
export const elementsDescription3 = z.lazy(() => {
  return z.object({
    format: descriptionFormat9,
    raw: z.string().optional(),
    html: z.string().optional(),
  });
});

/**
 *
 * @typedef  {ElementsDescription3} elementsDescription3
 * @property {DescriptionFormat9} - Indicates the formatting language of the raw text
 * @property {string} - The raw text, as entered by the user
 * @property {string} - The text converted to HTML according to the format
 */
export type ElementsDescription3 = z.infer<typeof elementsDescription3>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const elementsDescription3Response = z.lazy(() => {
  return z
    .object({
      format: descriptionFormat9,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const elementsDescription3Request = z.lazy(() => {
  return z
    .object({
      format: descriptionFormat9,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});
