// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const notificationCollectionModelType = z.literal('Collection');

export type NotificationCollectionModelType = z.infer<typeof notificationCollectionModelType>;
