// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const reason = z.union([
  z.literal('assigned'),
  z.literal('commented'),
  z.literal('created'),
  z.literal('dateAlert'),
  z.literal('mentioned'),
  z.literal('prioritized'),
  z.literal('processed'),
  z.literal('responsible'),
  z.literal('subscribed'),
  z.literal('scheduled'),
  z.literal('watched'),
]);

export type Reason = z.infer<typeof reason>;
