// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const schemaModelType = z.literal('Schema');

export type SchemaModelType = z.infer<typeof schemaModelType>;
