// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const relationCollectionModelType = z.literal('Collection');

export type RelationCollectionModelType = z.infer<typeof relationCollectionModelType>;
