// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const reverseType = z.union([
  z.literal('relates'),
  z.literal('duplicates'),
  z.literal('duplicated'),
  z.literal('blocks'),
  z.literal('blocked'),
  z.literal('precedes'),
  z.literal('follows'),
  z.literal('includes'),
  z.literal('partof'),
  z.literal('requires'),
  z.literal('required'),
]);

export type ReverseType = z.infer<typeof reverseType>;
