// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const availableAssigneesModelType = z.literal('Collection');

export type AvailableAssigneesModelType = z.infer<typeof availableAssigneesModelType>;
