// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const fileLinkCollectionWriteModelType = z.literal('Collection');

export type FileLinkCollectionWriteModelType = z.infer<typeof fileLinkCollectionWriteModelType>;
