// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { DescriptionFormat7, descriptionFormat7 } from './description-format-7';

/**
 * The shape of the model inside the application code - what the users use
 */
export const workPackageWriteModelDescription = z.lazy(() => {
  return z.object({
    format: descriptionFormat7,
    raw: z.string().optional(),
    html: z.string().optional(),
  });
});

/**
 * The work package description
 * @typedef  {WorkPackageWriteModelDescription} workPackageWriteModelDescription - The work package description - The work package description
 * @property {DescriptionFormat7} - Indicates the formatting language of the raw text
 * @property {string} - The raw text, as entered by the user
 * @property {string} - The text converted to HTML according to the format
 */
export type WorkPackageWriteModelDescription = z.infer<typeof workPackageWriteModelDescription>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const workPackageWriteModelDescriptionResponse = z.lazy(() => {
  return z
    .object({
      format: descriptionFormat7,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const workPackageWriteModelDescriptionRequest = z.lazy(() => {
  return z
    .object({
      format: descriptionFormat7,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});
