// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { DescriptionFormat8, descriptionFormat8 } from './description-format-8';

/**
 * The shape of the model inside the application code - what the users use
 */
export const workPackagePatchModelDescription = z.lazy(() => {
  return z.object({
    format: descriptionFormat8,
    raw: z.string().optional(),
    html: z.string().optional(),
  });
});

/**
 * The work package description
 * @typedef  {WorkPackagePatchModelDescription} workPackagePatchModelDescription - The work package description - The work package description
 * @property {DescriptionFormat8} - Indicates the formatting language of the raw text
 * @property {string} - The raw text, as entered by the user
 * @property {string} - The text converted to HTML according to the format
 */
export type WorkPackagePatchModelDescription = z.infer<typeof workPackagePatchModelDescription>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const workPackagePatchModelDescriptionResponse = z.lazy(() => {
  return z
    .object({
      format: descriptionFormat8,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const workPackagePatchModelDescriptionRequest = z.lazy(() => {
  return z
    .object({
      format: descriptionFormat8,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});
