// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const workPackageSchemaModelType = z.literal('Schema');

export type WorkPackageSchemaModelType = z.infer<typeof workPackageSchemaModelType>;
