// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const statusModelType = z.literal('Status');

export type StatusModelType = z.infer<typeof statusModelType>;
