// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const statusCollectionModelType = z.literal('Collection');

export type StatusCollectionModelType = z.infer<typeof statusCollectionModelType>;
