// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { _LinksSelf35, _linksSelf35, _linksSelf35Request, _linksSelf35Response } from './_links-self-35';

/**
 * The shape of the model inside the application code - what the users use
 */
export const groupCollectionModelLinks = z.lazy(() => {
  return z.object({
    self: _linksSelf35,
  });
});

/**
 * 
 * @typedef  {GroupCollectionModelLinks} groupCollectionModelLinks   
 * @property {_LinksSelf35} - This group collection

``Resource``: Collection
 */
export type GroupCollectionModelLinks = z.infer<typeof groupCollectionModelLinks>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const groupCollectionModelLinksResponse = z.lazy(() => {
  return z
    .object({
      self: _linksSelf35Response,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const groupCollectionModelLinksRequest = z.lazy(() => {
  return z
    .object({
      self: _linksSelf35Request,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});
