// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const groupCollectionModelType = z.literal('Collection');

export type GroupCollectionModelType = z.infer<typeof groupCollectionModelType>;
