// This file was generated by liblab | https://liblab.com/

export interface ListNotificationsParams {
  offset?: number;
  pageSize?: number;
  sortBy?: string;
  groupBy?: string;
  filters?: string;
}

export interface ReadNotificationsParams {
  filters?: string;
}

export interface UnreadNotificationsParams {
  filters?: string;
}
