// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  _EmbeddedElements3,
  _embeddedElements3,
  _embeddedElements3Request,
  _embeddedElements3Response,
} from './_embedded-elements-3';

/**
 * The shape of the model inside the application code - what the users use
 */
export const categoriesByProjectModelEmbedded = z.lazy(() => {
  return z.object({
    elements: z.array(_embeddedElements3).optional(),
  });
});

/**
 *
 * @typedef  {CategoriesByProjectModelEmbedded} categoriesByProjectModelEmbedded
 * @property {_EmbeddedElements3[]}
 */
export type CategoriesByProjectModelEmbedded = z.infer<typeof categoriesByProjectModelEmbedded>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const categoriesByProjectModelEmbeddedResponse = z.lazy(() => {
  return z
    .object({
      elements: z.array(_embeddedElements3Response).optional(),
    })
    .transform((data) => ({
      elements: data['elements'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const categoriesByProjectModelEmbeddedRequest = z.lazy(() => {
  return z
    .object({
      elements: z.array(_embeddedElements3Request).optional(),
    })
    .transform((data) => ({
      elements: data['elements'],
    }));
});
