// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const categoriesByProjectModelType = z.literal('Collection');

export type CategoriesByProjectModelType = z.infer<typeof categoriesByProjectModelType>;
