// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const oAuthClientCredentialsReadModelType = z.literal('OAuthClientCredentials');

export type OAuthClientCredentialsReadModelType = z.infer<typeof oAuthClientCredentialsReadModelType>;
