// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const oAuthApplicationReadModelType = z.literal('OAuthApplication');

export type OAuthApplicationReadModelType = z.infer<typeof oAuthApplicationReadModelType>;
