// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const projectStorageModelType = z.literal('ProjectStorage');

export type ProjectStorageModelType = z.infer<typeof projectStorageModelType>;
