// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const projectStorageCollectionModelType = z.literal('Collection');

export type ProjectStorageCollectionModelType = z.infer<typeof projectStorageCollectionModelType>;
