// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const projectFolderMode = z.union([z.literal('inactive'), z.literal('manual')]);

export type ProjectFolderMode = z.infer<typeof projectFolderMode>;
