// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const storageFilesModelType = z.literal('StorageFiles');

export type StorageFilesModelType = z.infer<typeof storageFilesModelType>;
