// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const storageFolderWriteModel = z.lazy(() => {
  return z.object({
    name: z.string(),
    parentId: z.string(),
  });
});

/**
 *
 * @typedef  {StorageFolderWriteModel} storageFolderWriteModel
 * @property {string} - Name of the folder to be created
 * @property {string} - Unique identifier of the parent folder in which the new folder should be created in
 */
export type StorageFolderWriteModel = z.infer<typeof storageFolderWriteModel>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const storageFolderWriteModelResponse = z.lazy(() => {
  return z
    .object({
      name: z.string(),
      parentId: z.string(),
    })
    .transform((data) => ({
      name: data['name'],
      parentId: data['parentId'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const storageFolderWriteModelRequest = z.lazy(() => {
  return z
    .object({
      name: z.string(),
      parentId: z.string(),
    })
    .transform((data) => ({
      name: data['name'],
      parentId: data['parentId'],
    }));
});
