// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  _EmbeddedElements1,
  _embeddedElements1,
  _embeddedElements1Request,
  _embeddedElements1Response,
} from './_embedded-elements-1';

/**
 * The shape of the model inside the application code - what the users use
 */
export const attachmentsEmbedded = z.lazy(() => {
  return z.object({
    elements: z.array(_embeddedElements1).optional(),
  });
});

/**
 *
 * @typedef  {AttachmentsEmbedded} attachmentsEmbedded
 * @property {_EmbeddedElements1[]}
 */
export type AttachmentsEmbedded = z.infer<typeof attachmentsEmbedded>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const attachmentsEmbeddedResponse = z.lazy(() => {
  return z
    .object({
      elements: z.array(_embeddedElements1Response).optional(),
    })
    .transform((data) => ({
      elements: data['elements'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const attachmentsEmbeddedRequest = z.lazy(() => {
  return z
    .object({
      elements: z.array(_embeddedElements1Request).optional(),
    })
    .transform((data) => ({
      elements: data['elements'],
    }));
});
