// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const attachmentsModelType = z.literal('Collection');

export type AttachmentsModelType = z.infer<typeof attachmentsModelType>;
