// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { DescriptionFormat1, descriptionFormat1 } from './description-format-1';

/**
 * The shape of the model inside the application code - what the users use
 */
export const elementsDescription1 = z.lazy(() => {
  return z.object({
    format: descriptionFormat1,
    raw: z.string().optional(),
    html: z.string().optional(),
  });
});

/**
 * A user provided description of the file
 * @typedef  {ElementsDescription1} elementsDescription1 - A user provided description of the file - A user provided description of the file
 * @property {DescriptionFormat1} - Indicates the formatting language of the raw text
 * @property {string} - The raw text, as entered by the user
 * @property {string} - The text converted to HTML according to the format
 */
export type ElementsDescription1 = z.infer<typeof elementsDescription1>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const elementsDescription1Response = z.lazy(() => {
  return z
    .object({
      format: descriptionFormat1,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const elementsDescription1Request = z.lazy(() => {
  return z
    .object({
      format: descriptionFormat1,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});
