// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { TimeEntryModel, timeEntryModel, timeEntryModelRequest, timeEntryModelResponse } from './time-entry-model';

/**
 * The shape of the model inside the application code - what the users use
 */
export const timeEntryCollectionModelEmbedded = z.lazy(() => {
  return z.object({
    elements: z.array(timeEntryModel),
  });
});

/**
 *
 * @typedef  {TimeEntryCollectionModelEmbedded} timeEntryCollectionModelEmbedded
 * @property {TimeEntryModel[]}
 */
export type TimeEntryCollectionModelEmbedded = z.infer<typeof timeEntryCollectionModelEmbedded>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const timeEntryCollectionModelEmbeddedResponse = z.lazy(() => {
  return z
    .object({
      elements: z.array(timeEntryModelResponse),
    })
    .transform((data) => ({
      elements: data['elements'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const timeEntryCollectionModelEmbeddedRequest = z.lazy(() => {
  return z
    .object({
      elements: z.array(timeEntryModelRequest),
    })
    .transform((data) => ({
      elements: data['elements'],
    }));
});
