// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { _LinksSelf16, _linksSelf16, _linksSelf16Request, _linksSelf16Response } from './_links-self-16';

/**
 * The shape of the model inside the application code - what the users use
 */
export const customOptionModelLinks = z.lazy(() => {
  return z.object({
    self: _linksSelf16,
  });
});

/**
 * 
 * @typedef  {CustomOptionModelLinks} customOptionModelLinks   
 * @property {_LinksSelf16} - This custom option.

``Resource``: CustomOption
 */
export type CustomOptionModelLinks = z.infer<typeof customOptionModelLinks>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const customOptionModelLinksResponse = z.lazy(() => {
  return z
    .object({
      self: _linksSelf16Response,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const customOptionModelLinksRequest = z.lazy(() => {
  return z
    .object({
      self: _linksSelf16Request,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});
