// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { _LinksSelf17, _linksSelf17, _linksSelf17Request, _linksSelf17Response } from './_links-self-17';

/**
 * The shape of the model inside the application code - what the users use
 */
export const nonWorkingDayCollectionModelLinks = z.lazy(() => {
  return z.object({
    self: _linksSelf17,
  });
});

/**
 * 
 * @typedef  {NonWorkingDayCollectionModelLinks} nonWorkingDayCollectionModelLinks   
 * @property {_LinksSelf17} - This non working days collection

``Resource``: NonWorkingDayCollectionModel
 */
export type NonWorkingDayCollectionModelLinks = z.infer<typeof nonWorkingDayCollectionModelLinks>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const nonWorkingDayCollectionModelLinksResponse = z.lazy(() => {
  return z
    .object({
      self: _linksSelf17Response,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const nonWorkingDayCollectionModelLinksRequest = z.lazy(() => {
  return z
    .object({
      self: _linksSelf17Request,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});
