// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { _LinksSelf19, _linksSelf19, _linksSelf19Request, _linksSelf19Response } from './_links-self-19';

/**
 * The shape of the model inside the application code - what the users use
 */
export const weekDayCollectionModelLinks = z.lazy(() => {
  return z.object({
    self: _linksSelf19,
  });
});

/**
 * 
 * @typedef  {WeekDayCollectionModelLinks} weekDayCollectionModelLinks   
 * @property {_LinksSelf19} - This week days collection

``Resource``: WeekDayCollectionModel
 */
export type WeekDayCollectionModelLinks = z.infer<typeof weekDayCollectionModelLinks>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const weekDayCollectionModelLinksResponse = z.lazy(() => {
  return z
    .object({
      self: _linksSelf19Response,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const weekDayCollectionModelLinksRequest = z.lazy(() => {
  return z
    .object({
      self: _linksSelf19Request,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});
