// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const weekDayCollectionModelType = z.literal('Collection');

export type WeekDayCollectionModelType = z.infer<typeof weekDayCollectionModelType>;
