// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  WeekDayCollectionWriteModelType,
  weekDayCollectionWriteModelType,
} from './week-day-collection-write-model-type';
import {
  WeekDayCollectionWriteModelEmbedded,
  weekDayCollectionWriteModelEmbedded,
  weekDayCollectionWriteModelEmbeddedRequest,
  weekDayCollectionWriteModelEmbeddedResponse,
} from './week-day-collection-write-model-embedded';

/**
 * The shape of the model inside the application code - what the users use
 */
export const weekDayCollectionWriteModel = z.lazy(() => {
  return z.object({
    _type: weekDayCollectionWriteModelType,
    _embedded: weekDayCollectionWriteModelEmbedded,
  });
});

/**
 *
 * @typedef  {WeekDayCollectionWriteModel} weekDayCollectionWriteModel
 * @property {WeekDayCollectionWriteModelType}
 * @property {WeekDayCollectionWriteModelEmbedded}
 */
export type WeekDayCollectionWriteModel = z.infer<typeof weekDayCollectionWriteModel>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const weekDayCollectionWriteModelResponse = z.lazy(() => {
  return z
    .object({
      _type: weekDayCollectionWriteModelType,
      _embedded: weekDayCollectionWriteModelEmbeddedResponse,
    })
    .transform((data) => ({
      _type: data['_type'],
      _embedded: data['_embedded'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const weekDayCollectionWriteModelRequest = z.lazy(() => {
  return z
    .object({
      _type: weekDayCollectionWriteModelType,
      _embedded: weekDayCollectionWriteModelEmbeddedRequest,
    })
    .transform((data) => ({
      _type: data['_type'],
      _embedded: data['_embedded'],
    }));
});
