// This file was generated by liblab | https://liblab.com/

export interface OpenFileLinkParams {
  location?: boolean;
}

export interface ListProjectStoragesParams {
  filters?: string;
}

export interface GetStorageFilesParams {
  parent?: string;
}
