// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const gridWidgetModelType = z.literal('GridWidget');

export type GridWidgetModelType = z.infer<typeof gridWidgetModelType>;
