// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const _linksSelf21 = z.lazy(() => {
  return z.object({
    href: z.string().nullable(),
    title: z.string().optional(),
    templated: z.boolean().optional(),
    method: z.string().optional(),
    payload: z.any().optional(),
    identifier: z.string().optional(),
    type: z.string().optional(),
  });
});

/**
 * This document

**Resource**: Document
 * @typedef  {_LinksSelf21} _linksSelf21 - This document

**Resource**: Document - This document

**Resource**: Document
 * @property {string} - URL to the referenced resource (might be relative)
 * @property {string} - Representative label for the resource
 * @property {boolean} - If true the href contains parts that need to be replaced by the client
 * @property {string} - The HTTP verb to use when requesting the resource
 * @property {any} - The payload to send in the request to achieve the desired result
 * @property {string} - An optional unique identifier to the link object
 * @property {string} - The MIME-Type of the returned resource.
 */
export type _LinksSelf21 = z.infer<typeof _linksSelf21>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const _linksSelf21Response = z.lazy(() => {
  return z
    .object({
      href: z.string().nullable(),
      title: z.string().optional(),
      templated: z.boolean().optional(),
      method: z.string().optional(),
      payload: z.any().optional(),
      identifier: z.string().optional(),
      type: z.string().optional(),
    })
    .transform((data) => ({
      href: data['href'],
      title: data['title'],
      templated: data['templated'],
      method: data['method'],
      payload: data['payload'],
      identifier: data['identifier'],
      type: data['type'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const _linksSelf21Request = z.lazy(() => {
  return z
    .object({
      href: z.string().nullable(),
      title: z.string().optional(),
      templated: z.boolean().optional(),
      method: z.string().optional(),
      payload: z.any().optional(),
      identifier: z.string().optional(),
      type: z.string().optional(),
    })
    .transform((data) => ({
      href: data['href'],
      title: data['title'],
      templated: data['templated'],
      method: data['method'],
      payload: data['payload'],
      identifier: data['identifier'],
      type: data['type'],
    }));
});
