// This file was generated by liblab | https://liblab.com/

import { OpenProjectApiV3Stable_, SdkConfig } from 'openproject-api-v3-stable';

/**
 * Helper to create a new SDK instance
 */
export function createSdkInstance(headers: Headers) {
  const config: SdkConfig = {
    username: headers.get('USERNAME') || process.env.USERNAME || '',
    password: headers.get('PASSWORD') || process.env.PASSWORD || '',
  };
  if (headers.get('BASE_URL') || process.env.BASE_URL) {
    config.baseUrl = headers.get('BASE_URL') || process.env.BASE_URL;
  }
  return new OpenProjectApiV3Stable_(config);
}

export type SDKProxy = ReturnType<typeof createSdkInstance>;
