// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { _LinksSelf74, _linksSelf74, _linksSelf74Request, _linksSelf74Response } from './_links-self-74';

/**
 * The shape of the model inside the application code - what the users use
 */
export const userCollectionModelLinks = z.lazy(() => {
  return z.object({
    self: _linksSelf74,
  });
});

/**
 * 
 * @typedef  {UserCollectionModelLinks} userCollectionModelLinks   
 * @property {_LinksSelf74} - This user collection

``Resource``: Collection
 */
export type UserCollectionModelLinks = z.infer<typeof userCollectionModelLinks>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const userCollectionModelLinksResponse = z.lazy(() => {
  return z
    .object({
      self: _linksSelf74Response,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const userCollectionModelLinksRequest = z.lazy(() => {
  return z
    .object({
      self: _linksSelf74Request,
    })
    .transform((data) => ({
      self: data['self'],
    }));
});
