// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const priorityCollectionModelType = z.literal('Collection');

export type PriorityCollectionModelType = z.infer<typeof priorityCollectionModelType>;
