// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const membershipSchemaModelType = z.literal('Schema');

export type MembershipSchemaModelType = z.infer<typeof membershipSchemaModelType>;
