// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { StatusExplanationFormat1, statusExplanationFormat1 } from './status-explanation-format-1';

/**
 * The shape of the model inside the application code - what the users use
 */
export const projectModelStatusExplanation = z.lazy(() => {
  return z.object({
    format: statusExplanationFormat1,
    raw: z.string().optional(),
    html: z.string().optional(),
  });
});

/**
 * A text detailing and explaining why the project has the reported status
 * @typedef  {ProjectModelStatusExplanation} projectModelStatusExplanation - A text detailing and explaining why the project has the reported status - A text detailing and explaining why the project has the reported status
 * @property {StatusExplanationFormat1} - Indicates the formatting language of the raw text
 * @property {string} - The raw text, as entered by the user
 * @property {string} - The text converted to HTML according to the format
 */
export type ProjectModelStatusExplanation = z.infer<typeof projectModelStatusExplanation>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const projectModelStatusExplanationResponse = z.lazy(() => {
  return z
    .object({
      format: statusExplanationFormat1,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const projectModelStatusExplanationRequest = z.lazy(() => {
  return z
    .object({
      format: statusExplanationFormat1,
      raw: z.string().optional(),
      html: z.string().optional(),
    })
    .transform((data) => ({
      format: data['format'],
      raw: data['raw'],
      html: data['html'],
    }));
});
