// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const projectCollectionModelType = z.literal('Collection');

export type ProjectCollectionModelType = z.infer<typeof projectCollectionModelType>;
