// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const projectModelType = z.literal('Project');

export type ProjectModelType = z.infer<typeof projectModelType>;
